name: Test

on:
  # workflow_call:  
  # Schedule makes this bot run in regular intervals, without any interventions
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ runner.os }}-pip-${{ hashFiles('./requirements-action.txt') }}
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements-action.txt
      - name: Run python scripts
        run: |
          python ./src/actiontest.py